# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c6a95eb030eb7ff84246a98520a2b19d"
name = "app-by-desmond"
handle = "app-by-desmond"
application_url = "https://causes-erp-photographers-oaks.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "store-by-desmond.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,write_orders,write_products"

[auth]
redirect_urls = [
  "https://causes-erp-photographers-oaks.trycloudflare.com/auth/callback",
  "https://causes-erp-photographers-oaks.trycloudflare.com/auth/shopify/callback",
  "https://causes-erp-photographers-oaks.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

  [[webhooks.subscriptions]]
  topics = [
  "app/uninstalled",
  "orders/create",
  "orders/delete",
  "orders/updated"
]
  uri = "/webhooks"

[pos]
embedded = false
